# Generated by Django 2.2.12 on 2020-05-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
